kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: buildly-service-discovery
subjects:
- kind: ServiceAccount
  name: buildly-service-discovery
roleRef:
  kind: Role
  name: buildly-service-discovery
  apiGroup: rbac.authorization.k8s.io
